<AnswerInput>:
    y: 200
    minimum_width: 300
    BoxLayout:
        orientation: "vertical"
        height: "200px"
        size_hint_y: None
        TextInput:
            size_hint_x: 0.5
            size_hint_y: 0.8
            focus: True
        Button:
            text: "Generate Wheel"
            background_color: "blue"
            font_size: 15
            size_hint_x: 0.5
            size_hint_y: 0.2